  
name        = "fftpack"
description = "FFTPACK is a package of Fortran subprograms for the fast Fourier transform of periodic and other symmetric sequences. It includes complex, real, sine, cosine, and quarter-wave transforms."
homepage    = "http://www.netlib.org/fftpack/"
version     = "1.0.0"
license     = "Public Domain"
author      = "Paul N. Swarztrauber"
maintainer  = "@fortran-lang"
copyright   = "Copyright 1985 National Center for Atmospheric Research, Boulder, CO"
categories  = ["Fast Fourier Transform"]
keywords    = ["netlib", "fft"]

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false